ServerEvents.recipes(event => 
	{
		event.remove({ id: 'create_dd:copycat_block_from_ingots_zinc_stonecutting'})
		event.remove({ id: 'create_dd:copycat_slab_from_ingots_zinc_stonecutting'})
		event.remove({ id: 'create_oppenheimered/compacting/amber_from_honey'})
		event.remove({ id: 'create_dd:superheating/netherite_scrap'})
		event.remove({ id: 'create_additions_synthetics:tank_conversion' })
		event.remove({ id: 'createqol:mixing/chromatic_compound'})
		event.remove({ id: 'alexscavesdelight:block/organic_compost'})
		event.remove({ id: 'create:crafting/palettes/scorchia' })
		event.remove({ id:  'create:crushing/uranium_ore'})
		event.remove({ id:  'create_alexscaves_compat:crushing/radrock_uranium_ore'})
		event.remove({ id:  'create_oppenheimered:crushing/uranium_ore'})
		event.remove({ id:  'create_oppenheimered:crushing/coprolith_coal_ore'})
		event.remove({ id:  'create_alexscaves_compat:crushing/coprolith_coal_ore'})
		event.remove({ id:  'create_alexscaves_compat:crushing/galena_iron_ore'})
		event.remove({ id:  'create_oppenheimered:crushing/galena_iron_ore'})
		event.remove({ id:  'create_oppenheimered:crushing/guanostone_redstone_ore'})
		event.remove({ id:  'create_alexscaves_compat:crushing/guanostone_redstone_ore'})
	}
)