ServerEvents.tags('block', event => 
    {
        // Tap Fillable
            event.add('fluid:tap_fillable', [
                "createmetallurgy:foundry_basin",
                "createmetallurgy:casting_basin",
                "createmetallurgy:casting_table"
            ])
        // Removes Scoria Tag from Cobblestone Generator Blocks
            event.remove('createcobblestone:generator_blocks', 'create:scoria')
            
        // Create Cobblestone Generator Types
            event.add('createcobblestone:generator_blocks',[
                'minecraft:stone',
                'create:limestone',
                'minecraft:cobblestone',
                'minecraft:basalt',
                'minecraft:dripstone_block',
                'regions_unexplored:chalk', 
                'regions_unexplored:mossy_stone', 
                'endelurgy:voidslate', 
                'minecraft:tuff', 
                'quark:jasper', 
                'minecraft:diorite', 
                'quark:shale', 
                'quark:myalite', 
                'minecraft:granite', 
                'minecraft:andesite', 
                'ad_astra:mercury_stone', 
                'create_dd:aethersite', 
                'ad_astra:venus_stone', 
                'quark:limestone', 
                'minecraft:blackstone', 
                'minecraft:calcite', 
                'create_dd:gabbro', 
                'ad_astra:glacio_stone', 
                'unusualend:warped_stone', 
                'minecraft:deepslate', 
                'ad_astra:mars_stone', 
                'ad_astra:moon_stone', 
                'unusualend:gloopstone', 
                'deeperdarker:gloomslate', 
                'deeperdarker:sculk_stone', 
                'alexscaves:limestone', 
                'unusualend:raw_purpur_block', 
                'alexscaves:guanostone', 
                'quark:permafrost', 
                'regions_unexplored:argillite',
                "echovoids:corrode_stone",
                "echovoids:corroded_entropite",
                "alexscaves:limestone"
            ])
            
        // Serene Seasons Tag
            event.add('sereneseasons:greenhouse_glass', '#minecraft:impermeable')

        // Forge Glass Tag
            event.add('forge:glass', '#minecraft:impermeable')
            
        // Steel Block
            event.add('forge:storage_blocks/steel', [
                'ad_astra:steel_block',
                'create_dd:steel_block'
            ])

        // Building Gadgets Deny Tag
            event.add('buildinggadgets2:deny', 'minecraft:spawner')
            
        // Beacon Base Blocks
            event.add('minecraft:beacon_base_blocks',[
                'forge_frontier:forge_rocket_casing'])

        // Spatial IO Blacklist
            event.add('ae2:blacklisted/spatial', 'minecraft:spawner')
        
        // Create Wrenchable
            event.add('create:wrench_pickup', [
                "refinedstorage:cable",
                '#quill:axe_blocks',
                '#forge:relocation_not_supported',
                "toms_storage:ts.crafting_terminal",
                "toms_storage:ts.inventory_cable_connector_filtered",
                "toms_storage:ts.inventory_cable_connector_framed",
                "toms_storage:ts.inventory_cable_connector",
                "toms_storage:ts.inventory_cable_framed",
                "toms_storage:ts.inventory_cable",
                "toms_storage:ts.inventory_connector",
                "toms_storage:ts.inventory_hopper_basic",
                "toms_storage:ts.inventory_proxy",
                "toms_storage:ts.level_emitter",
                "toms_storage:ts.open_crate",
                "toms_storage:ts.painted_trim",
                "toms_storage:ts.storage_terminal",
                "toms_storage:ts.trim",
                'createdeco:andesite_bars_overlay',
                'createdeco:andesite_bars',
                'createdeco:brass_bars_overlay',
                'createdeco:brass_bars',
                'createdeco:iron_bars_overlay',
                'createdeco:copper_bars_overlay',
                'createdeco:copper_bars',
                'createdeco:industrial_iron_bars_overlay',
                'createdeco:industrial_iron_bars',
                'createdeco:zinc_bars_overlay',
                'createdeco:zinc_bars',
                'createdeco:andesite_mesh_fence',
                'createdeco:brass_mesh_fence',
                'createdeco:iron_mesh_fence',
                'createdeco:copper_mesh_fence',
                'createdeco:industrial_iron_mesh_fence',
                'createdeco:zinc_mesh_fence',
                'createdeco:andesite_catwalk',
                'createdeco:andesite_catwalk_stairs',
                'createdeco:andesite_catwalk_railing',
                'createdeco:andesite_support_wedge',
                'createdeco:andesite_facade',
                'createdeco:brass_catwalk',
                'createdeco:brass_catwalk_stairs',
                'createdeco:brass_catwalk_railing',
                'createdeco:brass_support_wedge',
                'createdeco:brass_facade',
                'createdeco:iron_catwalk',
                'createdeco:iron_catwalk_stairs',
                'createdeco:iron_catwalk_railing',
                'createdeco:iron_support_wedge',
                'createdeco:iron_facade',
                'createdeco:copper_catwalk',
                'createdeco:copper_catwalk_stairs',
                'createdeco:copper_catwalk_railing',
                'createdeco:copper_support_wedge',
                'createdeco:copper_facade',
                'createdeco:industrial_iron_catwalk',
                'createdeco:industrial_iron_catwalk_stairs',
                'createdeco:industrial_iron_catwalk_railing',
                'createdeco:industrial_iron_support_wedge',
                'createdeco:industrial_iron_facade',
                'createdeco:zinc_catwalk',
                'createdeco:zinc_catwalk_stairs',
                'createdeco:zinc_catwalk_railing',
                'createdeco:zinc_support_wedge',
                'createdeco:zinc_facade',
                'createdeco:iron_ladder',
                'createdeco:industrial_iron_ladder',
                'createdeco:zinc_ladder',
                'createdeco:andesite_hull',
                'createdeco:brass_hull',
                'createdeco:iron_hull',
                'createdeco:copper_hull',
                'createdeco:industrial_iron_hull',
                'createdeco:zinc_hull',
                'createdeco:andesite_support',
                'createdeco:brass_support',
                'createdeco:iron_support',
                'createdeco:copper_support',
                'createdeco:industrial_iron_support',
                'createdeco:zinc_support',
                'createdeco:andesite_sheet_metal',
                'createdeco:brass_sheet_metal',
                'createdeco:iron_sheet_metal',
                'createdeco:copper_sheet_metal',
                'createdeco:industrial_iron_sheet_metal',
                'createdeco:zinc_sheet_metal',
                'createdeco:andesite_door',
                'createdeco:locked_andesite_door',
                'createdeco:andesite_trapdoor',
                'createdeco:brass_door',
                'createdeco:locked_brass_door',
                'createdeco:brass_trapdoor',
                'createdeco:copper_door',
                'createdeco:locked_copper_door',
                'createdeco:copper_trapdoor',
                'createdeco:industrial_iron_door',
                'createdeco:locked_industrial_iron_door',
                'createdeco:industrial_iron_trapdoor',
                'createdeco:zinc_door',
                'createdeco:locked_zinc_door',
                'createdeco:zinc_trapdoor',
                'createdeco:white_shipping_container',
                'createdeco:orange_shipping_container',
                'createdeco:magenta_shipping_container',
                'createdeco:light_blue_shipping_container',
                'createdeco:yellow_shipping_container',
                'createdeco:lime_shipping_container',
                'createdeco:pink_shipping_container',
                'createdeco:gray_shipping_container',
                'createdeco:light_gray_shipping_container',
                'createdeco:cyan_shipping_container',
                'createdeco:purple_shipping_container',
                'createdeco:blue_shipping_container',
                'createdeco:brown_shipping_container',
                'createdeco:green_shipping_container',
                'createdeco:red_shipping_container',
                'createdeco:black_shipping_container',
                'createdeco:orange_placard',
                'createdeco:magenta_placard',
                'createdeco:light_blue_placard',
                'createdeco:yellow_placard',
                'createdeco:lime_placard',
                'createdeco:pink_placard',
                'createdeco:gray_placard',
                'createdeco:light_gray_placard',
                'createdeco:cyan_placard',
                'createdeco:purple_placard',
                'createdeco:blue_placard',
                'createdeco:brown_placard',
                'createdeco:green_placard',
                'createdeco:red_placard',
                'createdeco:black_placard',
                '#create:chest_mounted_storage',
                'minecraft:cauldron',
                'minecraft:fletching_table',
                '#deeperdarker:transmittable',
                'sophisticatedstorage:shulker_box',
                'sophisticatedstorage:copper_shulker_box',
                'sophisticatedstorage:iron_shulker_box',
                'sophisticatedstorage:gold_shulker_box',
                'sophisticatedstorage:diamond_shulker_box',
                'sophisticatedstorage:netherite_shulker_box',
                'prettypipes:pressurizer',
                'prettypipes:item_terminal',
                'create:schematicannon',
                'create:schematic_table',
                'sophisticatedstorage:controller',
                'sophisticatedstorage:storage_link',
                'sophisticatedstorage:storage_io',
                'sophisticatedstorage:storage_input',
                'sophisticatedstorage:storage_output',
                'farmersdelight:cooking_pot',
                'farmersdelight:skillet',
                'farmersdelight:cutting_board',
                'aquaculture:tackle_box',
                'bobberdetector:bobber_detector',
                'hyperbox:hyperbox',
                'pipez:item_pipe',
                'pipez:fluid_pipe',
                'pipez:energy_pipe',
                'pipez:universal_pipe',
                'ad_astra:desh_fluid_pipe',
                'ad_astra:ostrum_fluid_pipe',
                'ad_astra:cable_duct',
                'ad_astra:fluid_pipe_duct',
                'ad_astra:coal_generator',
                'ad_astra:compressor',
                'ad_astra:etrionic_blast_furnace',
                'ad_astra:fuel_refinery',
                'ad_astra:oxygen_loader',
                'ad_astra:solar_panel',
                'ad_astra:water_pump',
                'ad_astra:oxygen_distributor',
                'ad_astra:gravity_normalizer',
                'ad_astra:energizer',
                'ad_astra:cryo_freezer',
                'ad_astra:oxygen_sensor',
                'ad_astra:launch_pad',
                'ad_astra:vent',
                'ad_astra:radio',
                'ad_astra_giselle_addon:gravity_normalizer',
                'ad_astra_giselle_addon:rocket_sensor',
                'ad_astra_giselle_addon:fuel_loader',
                'miners_delight:copper_pot',
                'farmersrespite:kettle',
                '#botanypots:all_botany_pots',
                '#chipped:lantern',
                '#chipped:soul_lantern',
                '#ad_astra:globes',
                '#ad_astra:sliding_doors',
                '#create:casing',
                'create_new_age:magnetite_block',
                'create_new_age:redstone_magnet',
                'create_new_age:layered_magnet',
                'create_new_age:fluxuated_magnetite',
                'create_new_age:netherite_magnet',
                'cabletiers:elite_exporter',
                'cabletiers:ultra_exporter',
                'cabletiers:mega_exporter',
                'cabletiers:elite_importer',
                'cabletiers:ultra_importer',
                'cabletiers:mega_importer',
                'cabletiers:elite_constructor',
                'cabletiers:ultra_constructor',
                'cabletiers:mega_constructor',
                'cabletiers:elite_destructor',
                'cabletiers:ultra_destructor',
                'cabletiers:mega_destructor',
                'cabletiers:elite_disk_manipulator',
                'cabletiers:ultra_disk_manipulator',
                'cabletiers:mega_disk_manipulator',
                'cabletiers:elite_interface',
                'cabletiers:ultra_interface',
                'cabletiers:mega_interface',
                'cabletiers:elite_requester',
                'cabletiers:ultra_requester',
                'cabletiers:mega_requester',
                "rsrequestify:requester",
                "rsrequestify:crafting_emitter",
                "merequester:requester",
                "merequester:requester_terminal",
                "exposer:exposer",
                "apokinetics:kinetic_pylon"
            ]);

    // Create Casing Tag
        event.add('create:casing', [
            'forge_frontier:forge_rocket_casing',
            'forge_frontier:steel_rocket_casing',
            'forge_frontier:desh_rocket_casing',
            'forge_frontier:ostrum_rocket_casing',
            'forge_frontier:calorite_rocket_casing',
            'forge_frontier:primal_magma_rocket_casing',
            'forge_frontier:enderite_rocket_casing',
        ]);

    // Adds Fan Processing Catalysts
        event.add('create_dd:fan_processing_catalysts_freezing', 'create_connected:fan_freezing_catalyst')
        event.add('create_dd:fan_processing_catalysts_superheating', 'create_connected:fan_seething_catalyst')
        event.add('createhalitosis:fan_processing_catalysts/halitosis', 'create_connected:fan_ending_catalyst_dragon_head')
    }
)