
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "Insufficient number of affixes to satisfy the loot rules", "Failed to execute LootRule", "Couldn't parse element loot_tables", "Couldn't load tag"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "Insufficient number of affixes to satisfy the loot rules", "Failed to execute LootRule", "Couldn't parse element loot_tables", "Couldn't load tag"]

