#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 06 19:56:36 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.7.1 + EuphoriaPatches_1.8.6
enableShaders=false
