#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 21 01:09:02 CDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.6.1 + Clrwl_1.0.2.zip
enableShaders=false
