#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Oct 04 00:30:21 CDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.5.1 + EuphoriaPatches_1.6.8 + Clrwl_1.0.0
enableShaders=false
